### ISSUE TITLE
requests-ntlm sends POST/PUT data three times

### ISSUE THREAD

**Issue by prokopst** [requests/requests-ntlm#87]
HttpNtlmAuth sends data three times for POST and PUT.

The flow is following:
- a program sends a POST/PUT request
- before the request is send, HttpNtlmAuth prepares the request, sets a hook on response
- the whole request is sent, data included
- server returns 401
- HttpNtlmAuth recognizes 401 and does retry_using_http_NTLM_auth
- sends the data again
- sends the data again, this time 200 is expected

This is quite fragile and slow, especially when you try to send a huge request - hundreds of MBs to a webdav server.

**Comment by Lukasa** [comment]
Yeah, this is a real problem, but there is very little we can do about it at the moment. Unfortunately, the way urllib3/requests is structured, it is not easily possible to intervene when sending data in situations like this to *conditionally* wait for an auth challenge that may or may not appear.

The easiest way to resolve this is to open a `Session` and send a `get` to a well-known URL when you do so in order to force the auth to happen earlier.

**Comment by prokopst** [comment]
> to conditionally wait for an auth challenge that may or may not appear.

I think I don't understand - I (the user) explicitly passed HttpNtlmAuth either to the request or to the session, so NTLM authentication is expected.

I would just:
* send the request without data if the connection is not authenticated and with prepared auth headers
* expect 401/407, otherwise fail horribly (hey user, you said you expect NTLM, but that's totally not true!)
* send the request with data and with the final auth headers
* expect 200

Or is the authentication expected to be just optional by any requests guideline?

**Comment by Lukasa** [comment]
@prokopst The auth challenge is expected by *the user*, but it may not appear. If we unconditionally waited for an auth challenge, that would impose a fixed latency on requests that expected auth but were not challenged, which is an unacceptable performance limitation.

The TL;DR is: yes, Requests expects auth to be optional, and if you aren't challenged then everything is ok.
